
istiod:
  global:
    logAsJson: true
  logging:
    level: "all:warn"

  pilot:
    autoscaleMin: 1
    autoscaleMax: 1
    replicaCount: 1
    env:
      ENABLE_NATIVE_SIDECARS: "true"
      # Inspired by https://istio.io/latest/docs/ops/configuration/traffic-management/dns-proxy/#dns-auto-allocation-v2
      PILOT_ENABLE_IP_AUTOALLOCATE: true

  meshConfig:
    outboundTrafficPolicy:
      mode: "REGISTRY_ONLY"
    defaultConfig:
      proxyMetadata:
        ISTIO_META_DNS_CAPTURE: true
