apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: temporal-custom-web
spec:
  hosts:
    - temporal.localhost
  gateways:
    - istio-ingress/istio-gateway-custom
  http:
    - route:
        - destination:
            host: temporal-custom-web.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
