gateway:
  name: istio-gateway-custom
  replicaCount: 1
  autoscaling:
    minReplicas: 1
    maxReplicas: 1
  service:
    type: LoadBalancer
    ports:
      - name: "http-status-port"
        port: 15100
        protocol: "TCP"
        targetPort: 15021
      - name: "http2"
        port: 80
        protocol: "TCP"
        targetPort: 80
      - name: "https"
        port: 443
        protocol: "TCP"
        targetPort: 443