keda:
  # Inspired by https://keda.sh/docs/2.16/integrations/istio-integration/
  podAnnotations:
    # -- Pod annotations for KEDA operator
    keda:
      traffic.sidecar.istio.io/excludeInboundPorts: "9666"
      traffic.sidecar.istio.io/excludeOutboundPorts: "9443,6443"
      prometheus.io/path: /metrics
      prometheus.io/port: '8080'
      prometheus.io/scrape: 'true'
    # -- Pod annotations for KEDA Metrics Adapter
    metricsAdapter:
      traffic.sidecar.istio.io/excludeInboundPorts: "6443"
      traffic.sidecar.istio.io/excludeOutboundPorts: "9666,9443"
    # -- Pod annotations for KEDA Admission webhooks
    webhooks:
      traffic.sidecar.istio.io/excludeInboundPorts: "9443"
      traffic.sidecar.istio.io/excludeOutboundPorts: "9666,6443"

  prometheus:
    operator:
      enabled: true