{{- $name := .Values.name | default dict }}
{{- range $val := .Values.externalServices.https }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $name }}-https-{{ $val.host | replace "*" "x" }}
spec:
  hosts:
    - {{ $val.host | quote }}
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: {{ $val.port | default 443 }}
      protocol: https
  resolution: {{ $val.resolution | default "DNS" }}
---
{{- end }}

