{{- if .Values.container.envSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: local
    kind: ClusterSecretStore
  target:
    name: {{ .Values.name }}
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      metadata:
        labels:
          app: {{ .Values.name }}
      data:
        {{- range $val := .Values.container.envSecret }}
        {{ $val.name | quote }}: {{ printf "\"{{ "}}.{{ $val.name }}{{ printf " }}\"" }}
        {{- end }}
  data:
    {{- range $val := .Values.container.envSecret }}
    - secretKey: {{ $val.name | quote }}
      remoteRef:
        key: {{ $val.key }}
    {{- end }}
{{- end }}
