apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    service: {{ .Values.name }}
  annotations:
    {{- if .Values.deployLink }}
    link.argocd.argoproj.io/deployLink: Deploy link|{{ .Values.deployLink }}
    {{- end }}
    link.argocd.argoproj.io/argo-rollouts: Argo Rollouts|http://argo-rollouts.{{ .Values.environment }}.in.localhost/rollouts/rollout/{{ .Release.Namespace }}/{{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.httpMainPort }}
      targetPort: http-main-port
    {{- range $additionalPort := .Values.service.additionalPorts }}
    - name: {{ $additionalPort.name }}
      port: {{ $additionalPort.port }}
      targetPort: {{ $additionalPort.targetContainerPortName }}
    {{- end }}
  selector:
    app: {{ .Values.name }}
