apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: 5678
      targetPort: 5678
  selector:
    service: n8n