raw:
  resources:
    - apiVersion : "networking.istio.io/v1alpha3"
      kind: "Gateway"
      metadata:
        name: "istio-gateway-custom"
        namespace: "istio-ingress"
      spec:
        selector:
          app: "istio-gateway-custom"
        servers:
          - hosts :
              - "*"
            port :
              name : "http2"
              number : 80
              protocol : "HTTP2"