apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: n8n
spec:
  hosts:
    - n8n.localhost
  gateways:
    - istio-ingress/istio-gateway-custom
  http:
    - route:
        - destination:
            host: n8n.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 5678